### ISSUE TITLE
[reframed] Invalid patching of `Document.getElementsBy*()` query methods

### ISSUE THREAD

**Issue by 1000hz** [web-fragments/web-fragments#60]
Currently, `reframed` attempts to patch some query methods on the iframe's `document` (particularly, `document.getElementsByClassName()`, `document.getElementsByTagName()`, and `document.getElementsByTagNameNS()`).

https://github.com/web-fragments/web-fragments/blob/317859ba60710c20e113385d8e9ef61dc9ce38f3/packages/reframed/src/reframed.ts#L456-L478
 It redirects these methods by calling them on the `shadowRoot` instead of the `document`. However, these three methods don't exist on the `ShadowRoot` interface, so these invoking them on the `document` results in the following error at runtime:

```
reframed.js:376 Uncaught TypeError: Cannot read properties of undefined (reading 'apply')
    at HTMLDocument.value [as getElementsByTagName]
```

We should instead invoke these methods on the shadow root's first element child (assuming we also ensure that we render the iframe content inside a single root child node.)

**Comment by IgorMinar** [comment]
Interesting. shadowRoot does support `querySelectorAll` but not the others. But fortunately all the other dom query apis can be expressed using `querySelectorAll` so this should be an easy fix.
