### ISSUE TITLE
Reframed - instanceof behavior with DOM Constructors fails

### ISSUE THREAD

**Issue by raycohen** [web-fragments/web-fragments#67]
In a fragment, `instanceof` checks used with DOM Constructors (like `NodeList`, `HTMLElement`, etc) will fail because the object was constructed in the parent window context, but the `instanceof` check will be against the iframe context which has an non-identical copy of those constructors.

Consider this example 3rd party code from OneTrust [otBannerSdk.js](https://cdn.cookielaw.org/scripttemplates/202304.1.0/otBannerSdk.js):
![onetrust-error](https://github.com/user-attachments/assets/516131cc-00a3-4b23-9b3c-6cfd1499ed8d)

In this code the `removeChild` function may be called with an instance of type `NodeList`, an instance of type `Array`, or an instance of type `HTMLElement`. If called with an array, the code works as expected because any array value that gets here would also be created in the iframe where this code is running. However, if it is called with a `NodeList` the code errors because the `e instanceof NodeList` check fails. This `NodeList` instance would have come from the parent via the patched `querySelectorAll`. The else condition is hit and the code errors because a NodeList has an undefined parentElement.

Instead, we need to check `e instanceof mainWindow.NodeList` for this to work. To support this, reframed could overwrite every DOM-related constructor in the iframe with the parent window's

```js
// inside monkeyPatchIFrameEnvironment

iframeWindow.HTMLButtonElement = mainWindow.HTMLButtonElement;
iframeWindow.HTMLElement = mainWindow.HTMLElement;
iframeWindow.HTMLHeadElement = mainWindow.HTMLHeadElement;
iframeWindow.NodeList = mainWindow.NodeList;
// ... and so on for many more constructors...
```

**Comment by IgorMinar** [comment]
Thanks for the contribution @raycohen! 🧡

I agree with you that we need to override the DOM constructors in the reframed context (within the iframe) as you suggested. Would you be open to sending us a PR with the changes or would you prefer that we make the changes ourselves?

We'd love more people to contribute, so we'd be happy to jump on call if needed to walk you through the PR creation process if needed.

**Comment by 1000hz** [comment]
I just opened #71 that should fix this. Instead of outright reassigning the constructors to the ones from the main context, I opted to add a `[Symbol.hasInstance]()` method to them to solely override `instanceof` behavior. It also extends all global constructors rather than attempting to keep up with maintaining a list of DOM constructors.
