### ISSUE TITLE
Reframed - patch window size properties

### ISSUE THREAD

**Issue by raycohen** [web-fragments/web-fragments#68]
Reframed apps that read [window.innerWidth](https://developer.mozilla.org/en-US/docs/Web/API/Window/innerWidth), `innerHeight`, `outerWidth`, and `outerHeight` will receive `0` due to the code running in a hidden iframe.

One example use for these values is for checking against hardcoded window width breakpoints to help control responsive behavior.

To work around this, these reads can be redefined to read from mainWindow.

```js
// add inside monkeyPatchIFrameEnvironment
Object.defineProperty(iframeWindow, "innerWidth", {
	get() {
		return mainWindow.innerWidth;
	},
});
Object.defineProperty(iframeWindow, "outerWidth", {
	get() {
		return mainWindow.outerWidth;
	},
});
Object.defineProperty(iframeWindow, "innerHeight", {
	get() {
		return mainWindow.innerHeight;
	},
});
// ...
```

I can open a PR with this if it is welcome.

**Comment by IgorMinar** [comment]
Another excellent find/suggestion @raycohen! Thank you. As mentioned at https://github.com/web-fragments/web-fragments/issues/67#issuecomment-2294408114, we'd be happy to accept a PR from you and assist with it's creation, or make the changes ourselves if you prefer that. Just let us know.
