### ISSUE TITLE
Patching document prototype impacts other Documents

### ISSUE THREAD

**Issue by raycohen** [web-fragments/web-fragments#73]
Any use of [createHTMLDocument](https://developer.mozilla.org/en-US/docs/Web/API/DOMImplementation/createHTMLDocument) in the reframed context will result in a Document instance that also has the same patches as the iframe document.

An example in practice is [this jquery code](https://github.com/jquery/jquery/blob/dbc9dac7aecb106b66050342ff8daf1ecdd4239f/test/data/jquery-3.7.1.js#L10125-L10134) that writes to the `body.innerHTML` on what it thinks is a throwaway document. However with the reframed patch, this will result in overwriting `shadowRoot.firstElementChild`.

Is there a reason these patches need to be on the prototype or could they be directly on the document instance?

**Comment by 1000hz** [comment]
Yeah, I agree these patches should be defined on the document itself rather than its prototype. It only makes sense for them to be applied to the document that's actually connected to the iframe's window.
